// <auto-generated />
namespace FinessaAesthetica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class PurchaseOrder_Update5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PurchaseOrder_Update5));
        
        string IMigrationMetadata.Id
        {
            get { return "201703031648007_PurchaseOrder_Update5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
