// <auto-generated />
namespace FinessaAesthetica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Status_Seeding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Status_Seeding));
        
        string IMigrationMetadata.Id
        {
            get { return "201702120318187_Status_Seeding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
