// <auto-generated />
namespace FinessaAesthetica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Model_Updates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_Updates));
        
        string IMigrationMetadata.Id
        {
            get { return "201702160550164_Model_Updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
