// <auto-generated />
namespace FinessaAesthetica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class BranchInventory_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BranchInventory_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201703011002531_BranchInventory_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
